version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  java-todo-app:
    build: .
    container_name: backend-java-todo-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
   
volumes:
  mongo-data:
    driver: local
